requirements: fix PyPi package interferences
A new version of Jinja2 was released that becomes incompatible
with Sphinx v3, since it removes some deprecated functions that
Sphinx is still using. Once Sphinx has patched the problem and
released a new version, Bridle should consider reverting this
band-aid fix.

For details see:

  - https://github.com/sphinx-doc/sphinx/issues/10291
  - https://github.com/pallets/jinja/issues/1585

Errors were:

  - ImportError: cannot import name 'environmentfilter' from 'jinja2'
  - ImportError: cannot import name 'soft_unicode' from 'markupsafe'

Signed-off-by: Stephan Linz <linz@li-pro.net>