snippets: tstdrv-bldall-sensor-adj: fixes for 64-bit native_sim
Disable ADXL362, ADXL367 and ADXL372 sensor drivers (at I2C and SPI),
because of compilation errors:

- zephyr/drivers/sensor/adi/adxl362/adxl362_decoder.c:
  In function ‘adxl362_decode_stream’:
    adxl362_decoder.c:92:6: error:
    adxl362_decoder.c:93:17: error:
      cast to pointer from integer of different size
- zephyr/drivers/sensor/adi/adxl367/adxl367_decoder.c:
  In function ‘adxl367_decode_stream’:
    adxl367_decoder.c:533:7: error:
    adxl367_decoder.c:534:18: error:
      cast to pointer from integer of different size
- zephyr/drivers/sensor/adi/adxl372/adxl372_decoder.c:
  In function ‘adxl372_decode_stream’:
    adxl372_decoder.c:61:6: error:
    adxl372_decoder.c:62:17: error:
      cast to pointer from integer of different size

Disable BMA4XX at I2C, because of test assertion failed at:

- zephyr/tests/drivers/build_all/sensor/src/generic_test.c:231:
  run_generic_test:
    expected_shifted not within actual_shifted +/- epsilon_shifted
    Expected -84238482048, got 84197349952
      shift 6, ch 0, iteration 1/5,
      Error -168435832000, Epsilon 41132032

Signed-off-by: Stephan Linz <linz@li-pro.net>