samples: ubx_gnss: remove deprecated Kconfigs
The following Kconfigs have been deprecated for more than 2
releases, remove them:

- CONFIG_MINIMAL_LIBC_MALLOC

Instead the new generic Kconfigs will used:

- CONFIG_COMMON_LIBC_MALLOC

This fixes following exemplary build error message since Zephyr
commit c22c98e51033379347cd8c681db34cf7afd33e57:

    /.../workspace/bridle/samples/ubx_gnss/prj.conf:31: warning:
      attempt to assign the value 'n' to the undefined symbol
      MINIMAL_LIBC_MALLOC

    error: Aborting due to Kconfig warnings

Signed-off-by: Stephan Linz <linz@li-pro.net>