snippets: tstdrv-bldall-sensor-adj: fixes for 64-bit native_sim
Disable ADXL366 sensor drivers (at I2C and SPI), because of
compilation errors:

- zephyr/drivers/sensor/adi/adxl367/adxl367_decoder.c:
  In function ‘adxl367_decode_stream’:
    adxl367_decoder.c:533:7: error:
    adxl367_decoder.c:534:18: error:
      cast to pointer from integer of different size

Signed-off-by: Stephan Linz <linz@li-pro.net>