ci: github-script: cope with V5 breaking changes
The actions/github-script was recently updated from v3.1.0 to v6
to catch Node 16 (f49acac1ef17b61f5945621ac99e4d7a3049a3a6), but
unfortunately there were breaking changes in the API with v5:

* https://github.com/actions/github-script#breaking-changes-in-v5
* https://github.com/actions/github-script/issues/242 (comment)

Error was manifest as:

TypeError: Cannot read properties of undefined
           (reading 'listWorkflowRunArtifacts')

So update our code to to use the new way to do things.

issues: #62 #64

Signed-off-by: Stephan Linz <linz@li-pro.net>