ci: github: qa: disable test report annotation
Due to the rapidly increasing number of tests and samples against all
supported platforms, the underlying build infrastructure is currently
experiencing persistent failures in the GitHub action responsible for
annotating the generated test reports. This is now leading to near
daily false-positive failures of the entire QA test chain due to the
following error message, even at the end of successfully completed
test runs:

    Error: timed out waiting for file … … …

Until a solution can be found, the processing and display of test
results for the samples will be disabled, in the hope that fewer
false alarms will be triggered from now on. The QA test chain should
only fail and trigger an alert in the event of actual errors.

Signed-off-by: Stephan Linz <linz@li-pro.net>