boards: magpie_f777ni: remove deprecated Kconfigs
These clock selection Kconfigs should have been deprecated for
more than 2 releases, remove them:

- CONFIG_COUNTER_RTC_STM32_CLOCK_SRC
- CONFIG_COUNTER_RTC_STM32_CLOCK_LSE

Instead favor of device tree secondary domain clock.

This fixes following exemplary build error message since Zephyr
commit 88c96f7986d408fae48cb538d8144c0aa985edb1:

    warning: <choice COUNTER_RTC_STM32_CLOCK_SRC>
    (defined at /.../boards/tiac/magpie_f777ni/Kconfig.defconfig:9)
    defined without a prompt

    warning: the default selection COUNTER_RTC_STM32_CLOCK_LSE
    (undefined) of <choice COUNTER_RTC_STM32_CLOCK_SRC>
    (defined at /.../boards/tiac/magpie_f777ni/Kconfig.defconfig:9)
    is not contained in the choice

    error: Aborting due to Kconfig warnings

Signed-off-by: Stephan Linz <linz@li-pro.net>